version: 2.1
jobs:
  build:
    working_directory: ~/route-guide
    docker:
    - image: cimg/clojure:1.11.1-openjdk-17.0
    steps:
    - checkout
    - restore_cache:
        key: route-guide-{{ checksum "project.clj" }}
    - run: lein deps
    # TODO: Implement tests
    # - run: lein test-coverage
    # TODO: Fix linter settings
    # - run: lein lint
    - run:
        name: Install static code analysis tools
        environment:
          CLJSTYLE_VERSION: 0.16.626
          CLJ_KONDO_VERSION: 2023.12.15
          JOKER_VERSION: 1.3.4
        command: |
          # cljstyle
          wget https://github.com/greglook/cljstyle/releases/download/${CLJSTYLE_VERSION}/cljstyle_${CLJSTYLE_VERSION}_linux_amd64.zip
          unzip -qq cljstyle_${CLJSTYLE_VERSION}_linux_amd64.zip
          sudo mv -f cljstyle /usr/local/bin/
          # clj-kondo
          curl -sLO https://raw.githubusercontent.com/borkdude/clj-kondo/master/script/install-clj-kondo
          chmod +x install-clj-kondo
          sudo ./install-clj-kondo --version ${CLJ_KONDO_VERSION}
          # Joker
          wget https://github.com/candid82/joker/releases/download/v${JOKER_VERSION}/joker-linux-amd64.zip
          unzip -qq joker-linux-amd64.zip
          sudo mv -f joker /usr/local/bin/
    - run: make lint
    # TODO: Enable Codecove
    # - run: bash <(curl -s https://codecov.io/bash) -f '!*.txt'
    - save_cache:
        key: route-guide-{{ checksum "project.clj" }}
        paths:
        - ~/.lein
        - ~/.m2
    # TODO: Implement tests
    # - run:
    #     name: Save test results
    #     command: |
    #       mkdir -p ~/test-results/clojure-test
    #       if [ -f target/coverage/junit.xml ]; then
    #         cp target/coverage/junit.xml ~/test-results/clojure-test/
    #       fi
    #     when: always
    # - store_test_results:
    #     path: ~/test-results
